<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LLLGMOJ" failures="0" tests="2" name="testngsamples.Actitime_ExceptionAndTimeout" time="1.043" errors="2" timestamp="19 Sep 2022 04:18:45 GMT" skipped="0">
  <testcase classname="testngsamples.Actitime_ExceptionAndTimeout" name="dividedByZeroExample1" time="0.018">
    <error message="
Expected exception of type class java.lang.ArithmeticException but got java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.ArithmeticException but got java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at testngsamples.Actitime_ExceptionAndTimeout.dividedByZeroExample1(Actitime_ExceptionAndTimeout.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 19 more
]]>
    </error>
  </testcase> <!-- dividedByZeroExample1 -->
  <testcase classname="testngsamples.Actitime_ExceptionAndTimeout" name="executetimeOut" time="1.025">
    <error message="Method testngsamples.Actitime_ExceptionAndTimeout.executetimeOut() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngsamples.Actitime_ExceptionAndTimeout.executetimeOut() didn't finish within the time-out 1000
at java.base@17.0.4.1/java.lang.invoke.MethodType.checkPtypes(MethodType.java:205)
at java.base@17.0.4.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:348)
at java.base@17.0.4.1/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:399)
at java.base@17.0.4.1/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- executetimeOut -->
</testsuite> <!-- testngsamples.Actitime_ExceptionAndTimeout -->
